### ISSUE TITLE
Add Types and Heaps Array in Vulkan Binding

### ISSUE THREAD

**Issue by achtzwan** [Ultz/Silk.NET#164] opened 2020-04-05 15:39 UTC
# Summary of feature
Would it be possible to add arrays like in the original Vulkan API to Silk.NET.Vulkan.PhysicalDeviceMemoryProperties.cs

```csharp
public MemoryType[] MemoryTypes;
public MemoryHeap[] MemoryHeaps;
```

It will reduce our code base a lot, because we don't have to create an array of it/switch through the struct anymore.

**Comment by Perksey** [comment] 2020-04-05 15:40
Duplicate of #163

**Closed by Perksey** 2020-04-05 15:40 UTC
Labels: enhancement
