### ISSUE TITLE
Vulkan Triange sample fails to run due to extension not being found

### ISSUE THREAD

**Issue by define-private-public** [Ultz/Silk.NET#251] opened 2020-07-20 00:55 UTC
# Summary
I've been learning Vulkan recently and wanted to take these bindings out for a spin.  I did full "Hello Triangle" sample in C++ on my machine and got it to display properly.

I tried doing `dotnet run` on VulkanTriangle sample and this was put out on my console:
```Unhandled exception. System.NotSupportedException: KHR_surface extension not found.
   at VulkanTriangle.HelloTriangleApplication.CreateInstance() in /home/ben/Projects/third_party/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 279
   at VulkanTriangle.HelloTriangleApplication.InitVulkan() in /home/ben/Projects/third_party/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 89
   at VulkanTriangle.HelloTriangleApplication.Run() in /home/ben/Projects/third_party/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 30
   at VulkanTriangle.Program.Main(String[] args) in /home/ben/Projects/third_party/Silk.NET/src/Lab/VulkanTriangle/Program.cs:line 10
```

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3.1
- API: Vulkan
- API Version: Vulkan 1.2

**Comment by HurricanKai** [comment] 2020-07-20 10:32
This suggests the KHR_swapchain extension was not found. Try running the "Vulkan Info" executable that's delivered with the SDK (on windows at least)
in the section "Device Extensions" `VK_KHR_swapchain` should be listed somewhere, if it is not, I believe your device is incompatible.

**Comment by Perksey** [comment] 2020-08-28 20:16
Closing as can't reproduce

**Closed by Perksey** 2020-08-28 20:16 UTC
Labels: bug
