### ISSUE TITLE
Multiple calls to GetInput extension lead to new glfw input contexts

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#80] opened 2019-12-22 13:33 UTC
# Summary
Multiple calls to the GetInput extension will create a new glfw input context each time. Therefore event registering on other than the first input context will not raise the events.

# Steps to reproduce
- Platform: Any
- Framework Version: Any
1. Create one method for initialize keyboard events and one for initialize mouse events.
2. In each method use GetInput() to retrieve the input context and add event handlers for keyboard events (first method) and mouse events (second method).
3. Mouse event callbacks are not called as the used input context is not considered by Silk. Only the first one is.

The problem is the method GetInput below. It creates a new instance of the input context instead of reusing the existing one if present.

```csharp
    public class GlfwInputPlatform : IInputPlatform
    {
        public bool IsApplicable(IWindow window)
        {
            return window is GlfwWindow;
        }

        public IInputContext GetInput(IWindow window)
        {
            // the cast isn't needed, but is used to make sure that what we've got is actually a GlfwWindow
            return new GlfwInputContext((GlfwWindow)window); // <- Problem, should reuse context when called for the second time
        }
    }
```

# Possible solutions
- Reuse context on second and subsequent calls
- Documentation that each time it is called a new context is created (in this case rename to `CreateInput`)
- Make Silk register each of the created contexts and ensure that all of them are handled

I would prefer first fix.

**Comment by Perksey** [comment] 2019-12-22 13:34
This is by design, you should really only be calling GetInput once and keeping track of the input context.

**Comment by Perksey** [comment] 2019-12-22 13:35
Although I guess we could change it, idk @Ultz/silk-working-group what do you think?

**Comment by Pyrdacor** [comment] 2019-12-22 13:37
If you want to keep it this way, then this must be documented better. Moreover a method labeled "GetXYZ" should have no side-effects by design. I would not expect that a new context is created. This should be renamed to `CreateInput` imho.

**Comment by Perksey** [comment] 2019-12-22 13:46
Yeah I 100% agree with you. The only reason we purposely made it so that it creates a new context is we wanted to avoid people going window.GetInput().blah for every single input call as that’s a code smell.

**Comment by Perksey** [comment] 2019-12-22 13:47
I’ll put it up to an working group vote now.

**Comment by Pyrdacor** [comment] 2019-12-22 14:20
You can rename it to `CreateInput` to avoid your mentioned case.

**Comment by Perksey** [comment] 2020-01-05 20:18
This was prematurely closed as this change was not implemented in InputWindowExtensions.

**Closed** 2020-01-30 17:36 UTC
Labels: bug
